version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.0.0

    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn install && yarn build

      - run: cp ./now.json ./public

      - run: sudo npm install --global --unsafe-perm now@13.1.2

      - run: now -t $NOW_TOKEN && now -t $NOW_TOKEN alias
